// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static dynamic get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const Map<String, dynamic> web = {
    'apiKey': 'AIzaSyAwUBJ_00XEtvNbz9TKLF-BFBgQflktLbw',
    'appId': '1:462980346178:web:c8a8e9f5eeabb596c658db',
    'messagingSenderId': '462980346178',
    'projectId': 'wcm-ministry',
    'authDomain': 'wcm-ministry.firebaseapp.com',
    'storageBucket': 'wcm-ministry.firebasestorage.app',
    'measurementId': 'G-2K9VXP8N1Z',
  };

  static const Map<String, dynamic> android = {
    'apiKey': 'AIzaSyAwUBJ_00XEtvNbz9TKLF-BFBgQflktLbw',
    'appId': '1:462980346178:android:your_android_app_id',
    'messagingSenderId': '462980346178',
    'projectId': 'wcm-ministry',
    'storageBucket': 'wcm-ministry.firebasestorage.app',
  };

  static const Map<String, dynamic> ios = {
    'apiKey': 'AIzaSyAwUBJ_00XEtvNbz9TKLF-BFBgQflktLbw',
    'appId': '1:462980346178:ios:your_ios_app_id',
    'messagingSenderId': '462980346178',
    'projectId': 'wcm-ministry',
    'storageBucket': 'wcm-ministry.firebasestorage.app',
    'iosBundleId': 'com.example.wcm',
  };

  static const Map<String, dynamic> macos = {
    'apiKey': 'AIzaSyAwUBJ_00XEtvNbz9TKLF-BFBgQflktLbw',
    'appId': '1:462980346178:macos:your_macos_app_id',
    'messagingSenderId': '462980346178',
    'projectId': 'wcm-ministry',
    'storageBucket': 'wcm-ministry.firebasestorage.app',
    'iosBundleId': 'com.example.wcm',
  };

  static const Map<String, dynamic> windows = {
    'apiKey': 'AIzaSyAwUBJ_00XEtvNbz9TKLF-BFBgQflktLbw',
    'appId': '1:462980346178:windows:your_windows_app_id',
    'messagingSenderId': '462980346178',
    'projectId': 'wcm-ministry',
    'storageBucket': 'wcm-ministry.firebasestorage.app',
  };
} 